# TODO: Should create admin in a seed. No need for user input.
# Was asked by akhil sir to do by rake task
#FIXME_AB: Yes I asked it to make a rake and ask user for admin details, so all people installing this app have different admin credentials. Lets do that way.
# Fixed , I did it that way, but then Shubham sir asked to change it to this pattern.
namespace :admin do
  # TODO: Why TODO??
  # It was generated by scaffold, I don't think I need it. Commenting for now
  # desc "TODO"
  task create: :environment do
    #FIXME_AB: Use Time.current
    # Fixed
    a = Admin.create(name: 'admin', email: 'mail2freeka@gmail.com', address: 'patel nagar', about_me: '..', contact_no: '5555', password: 'jjjjjjjj', confirmed_at: Time.current)
    p a.save
    puts 'Admin created with '
    puts a.email
    puts a.password
  end

end
